name: 'Reload pythonanywhere webapp'
description: 'GitHub action to reload a webapp on pythonanywhere'
inputs:
  username:
    description: 'Username for pythonanywhere'
    required: true
  api-token: 
    description: 'API token for pythonanywhere'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: refresh-cw
  color: green
